name: cesarebattista
favicon: null
layout_spectrum: 0.8399564248975366
typography_spectrum: 0.5312677775509655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.943705353885889
  lightness: 0.9682444869540632
  saturation: 0.46817288850434124
  rhythmicContrast: 0.3744741496630013
purpose: []
